# 应用名称
spring:
  application:
    name: base-samples
  profiles:
    active:
# druid
  datasource:
    druid:
      url: jdbc:p6spy:mysql://10.100.15.50:3306/app_skeleton?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: xsmysql
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      initial-size: 10
      min-idle: 10
      max-active: 100
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query: SELECT 1
      validation-query-timeout: 1000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 300000

#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
elasticjob:
  # 注册中心配置
  reg-center:
    # host1:2181,host2:2181
    serverLists: 10.100.14.89:2181,10.100.14.90:2181,10.100.14.91:2181
    namespace: BaseSamplesApplicationTests
    baseSleepTimeMilliseconds: 1000
    maxSleepTimeMilliseconds: 60000
    maxRetries: 3
    sessionTimeoutMilliseconds: 60000
    connectionTimeoutMilliseconds: 15000
    # 连接 ZooKeeper 的权限令牌
    digest:
  # 任务执行记录跟踪配置
  tracing:
    type: RDB
    dataSource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.100.15.50:3306/job_event_storage?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: xsmysql
    includeJobNames:
    excludeJobNames:
  # 任务定义
  jobs:
    MySimpleJob:
      elasticJobClass: cn.imadc.application.base.samples.elasticjob.MySimpleJob
      cron: 0/5 * * * * ?
      timeZone: GMT+08:00
      sharding-total-count: 3
      sharding-item-parameters: "0=Beijing,1=Shanghai,2=Guangzhou"
      failover: false
      misfire: true
      overwrite: true
    MySimpleJob1:
      elasticJobClass: cn.imadc.application.base.samples.elasticjob.MySimpleJob1
      cron: 0/5 * * * * ?
      timeZone: GMT+08:00
      sharding-total-count: 3
      sharding-item-parameters: "0=Beijing,1=Shanghai,2=Guangzhou"
      failover: false
      misfire: true
      jobParameter: "12312"
      overwrite: true