# 应用名称
spring:
  application:
    name: base-samples
  profiles:
    active:
# rocketmq
rocketmq:
  # host:port;host:port
  name-server: 10.100.2.51:9876;10.100.13.106:9876
  producer:
    group: PID_BASE_SAMPLES_DEV
    sendMessageTimeout: 3000
    retryTimesWhenSendFailed: 2
    retryTimesWhenSendAsyncFailed: 2
    retryNextServer: false
    access-key: xsbankRocketmq
    secret-key: xsbankP@ssw0rd
    enableMsgTrace: true
  consumer:
    access-key: xsbankRocketmq
    secret-key: xsbankP@ssw0rd
    topic-biz-a: TOPIC_BA_DEMO_DEV
    consumer-biz-a: CID_BA_DEMO_DEV
